/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"

//==============================================================================
/**
*/
class TIAAudioProcessorEditor  : public slAudioProcessorEditor
{
public:
    TIAAudioProcessorEditor (TIAAudioProcessor&);
    ~TIAAudioProcessorEditor();

    //==============================================================================
    void resized() override;
    void paint (Graphics& g) override;

    TIAAudioProcessor& processor;
    
    drow::TriggeredScope scope;
    Image logo;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TIAAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
