/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "slCommon.h"
#include "../../3rdparty/TIASound.h"

//==============================================================================
/**
*/
class TIAAudioProcessorEditor;
class TIAAudioProcessor : public slProcessor
{
public:
    //==============================================================================
    TIAAudioProcessor();
    ~TIAAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    
    static const char* paramPulse1Level;
    static const char* paramPulse1Tune;
    static const char* paramPulse1Fine;
    static const char* paramPulse1Shape;

    static const char* paramPulse2Level;
    static const char* paramPulse2Tune;
    static const char* paramPulse2Fine;
    static const char* paramPulse2Shape;
    
private:
    void runUntil (int& done, AudioSampleBuffer& buffer, int pos);
    
    int lastNote = -1;
    int velocity = 0;
    Array<int> noteQueue;
    
    LinearSmoothedValue<float> outputSmoothed;
    Component::SafePointer<TIAAudioProcessorEditor> editor;
    
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TIAAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
